"""V1 哨兵脚本的生成与清理 —— 探针 `probe.sentinel` 的生产移植。

filter 只认日志里 `__probe_` 前缀的人造边，不写文件。本模块负责：
扫描项目内 *.gd → 按相对路径排序 → 写入 res://__probe_sentinel.gd → 用完删除。

默认只 preload `.gd`（N07：shader 走 V3，不靠扩展哨兵）。排除 `__probe_` 前缀
和 `.godot/`，避免扫到缓存里的生成脚本或哨兵自身。
"""

from __future__ import annotations

from pathlib import Path

from godot_mcp.verify.commands import SENTINEL_RES_PATH

SENTINEL_FILENAME = "__probe_sentinel.gd"
_HELPER_PREFIX = "__probe_"
_EXCLUDE_DIR = ".godot"


def sentinel_path(project_root: Path) -> Path:
    return Path(project_root) / SENTINEL_FILENAME


def list_gd_resources(project_root: Path) -> list[str]:
    """返回排序后的 `res://...gd` 列表，排除哨兵自身与 `.godot/`。"""
    root = Path(project_root)
    resources: list[str] = []
    if not root.is_dir():
        return resources
    for path in sorted(root.rglob("*.gd")):
        if not path.is_file():
            continue
        try:
            rel = path.relative_to(root)
        except ValueError:
            continue
        if _EXCLUDE_DIR in rel.parts:
            continue
        if path.name.startswith(_HELPER_PREFIX):
            continue
        resources.append(f"res://{rel.as_posix()}")
    return resources


def build_sentinel_source(project_root: Path) -> str:
    """生成哨兵脚本正文。空项目也要能被 Godot 解析。"""
    resources = list_gd_resources(project_root)
    lines = [
        "extends RefCounted",
        "# generated by godot_mcp.verify.sentinel; not part of the project",
    ]
    for i, res in enumerate(resources):
        lines.append(f'const _p{i} = preload("{res}")')
    if not resources:
        lines.append("func _init() -> void:")
        lines.append("    pass")
    return "\n".join(lines) + "\n"


def install_sentinel(project_root: Path) -> Path:
    """写入 `res://__probe_sentinel.gd`，返回磁盘路径。"""
    dest = sentinel_path(project_root)
    dest.write_text(build_sentinel_source(project_root), encoding="utf-8")
    return dest


def remove_sentinel(project_root: Path) -> None:
    """删除哨兵文件；文件不存在时静默成功。"""
    dest = sentinel_path(project_root)
    try:
        dest.unlink()
    except FileNotFoundError:
        return


# 给测试/文档对照用：与 commands.SENTINEL_RES_PATH 必须一致
assert SENTINEL_RES_PATH == f"res://{SENTINEL_FILENAME}"
